/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class FormCekNomor extends javax.swing.JFrame {

    /**
     * Creates new form FormCekNomor
     */
    public FormCekNomor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHasil = new javax.swing.JLabel();
        txtAngka = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 153, 0))); // NOI18N

        lblHasil.setBackground(new java.awt.Color(255, 255, 255));
        lblHasil.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        lblHasil.setForeground(new java.awt.Color(255, 255, 255));
        lblHasil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHasil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        txtAngka.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAngka.setToolTipText("Masukan angka di sini");
        txtAngka.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        txtAngka.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAngkaFocusGained(evt);
            }
        });
        txtAngka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAngkaKeyTyped(evt);
            }
        });

        btnCek.setBackground(new java.awt.Color(255, 0, 0));
        btnCek.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCek.setForeground(new java.awt.Color(255, 255, 255));
        btnCek.setText("Enter");
        btnCek.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnCek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAngka, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 540, 160));

        jDesktopPane1.setBackground(new java.awt.Color(0, 255, 102));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Aplikasi Cek Nomor Ganjil Genap");

        jDesktopPane1.setLayer(lblJudul, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblJudul)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblJudul)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        String input = txtAngka.getText().trim();
                                         

    if (input.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Input tidak boleh kosong!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int angka = Integer.parseInt(input);

        // Cek Genap atau Ganjil
        String hasil;
        if (angka % 2 == 0) {
            hasil = angka + " adalah bilangan GENAP";
        } else {
            hasil = angka + " adalah bilangan GANJIL";
        }

        // Cek Bilangan Prima (Variasi)
        if (isPrima(angka)) {
            hasil += " dan juga BILANGAN PRIMA";
        }

        lblHasil.setText(hasil);
        javax.swing.JOptionPane.showMessageDialog(this, hasil, "Hasil Cek", javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Input harus berupa angka!", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    
    }//GEN-LAST:event_btnCekActionPerformed
    }
    private void txtAngkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngkaKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
        evt.consume(); // mencegah input non-angka
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Hanya boleh angka!", 
                "Peringatan", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_txtAngkaKeyTyped
    }
    
    private void txtAngkaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAngkaFocusGained
        txtAngka.setText("");
        lblHasil.setText("");  // kosongkan hasil saat fokus kembali ke input
    }//GEN-LAST:event_txtAngkaFocusGained
    

    private boolean isPrima(int n) {
        if (n <= 1) return false;
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) return false;
        }
        return true;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCekNomor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCekNomor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCekNomor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCekNomor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCekNomor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField txtAngka;
    // End of variables declaration//GEN-END:variables
}
